/**
* This file was automatically generated by `npm run generate-types:swapi`.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run `npm run generate-types:swapi` to regenerate this file.
*/

/**
 * A Star Wars film
 */
export interface Film {
  /**
   * The title of this film.
   */
  title: string;
  /**
   * The episode number of this film.
   */
  episode_id: number;
  /**
   * The opening crawl text at the beginning of this film.
   */
  opening_crawl: string;
  /**
   * The director of this film.
   */
  director: string;
  /**
   * The producer(s) of this film.
   */
  producer: string;
  /**
   * The release date at original creator country.
   */
  release_date: string;
  /**
   * The people resources featured within this film.
   */
  characters: string[];
  /**
   * The planet resources featured within this film.
   */
  planets: string[];
  /**
   * The starship resources featured within this film.
   */
  starships: string[];
  /**
   * The vehicle resources featured within this film.
   */
  vehicles: string[];
  /**
   * The species resources featured within this film.
   */
  species: string[];
  /**
   * The url of this resource
   */
  url: string;
  /**
   * The ISO 8601 date format of the time that this resource was created.
   */
  created: string;
  /**
   * the ISO 8601 date format of the time that this resource was edited.
   */
  edited: string;
  [k: string]: unknown;
}

/**
 * A person within the Star Wars universe
 */
export interface People {
  /**
   * The name of this person.
   */
  name: string;
  /**
   * The height of this person in meters.
   */
  height: string;
  /**
   * The mass of this person in kilograms.
   */
  mass: string;
  /**
   * The hair color of this person.
   */
  hair_color: string;
  /**
   * The skin color of this person.
   */
  skin_color: string;
  /**
   * The eye color of this person.
   */
  eye_color: string;
  /**
   * The birth year of this person. BBY (Before the Battle of Yavin) or ABY (After the Battle of Yavin).
   */
  birth_year: string;
  /**
   * The gender of this person (if known).
   */
  gender: string;
  /**
   * The url of the planet resource that this person was born on.
   */
  homeworld: string;
  /**
   * An array of urls of film resources that this person has been in.
   */
  films: string[];
  /**
   * The url of the species resource that this person is.
   */
  species: string[];
  /**
   * An array of vehicle resources that this person has piloted
   */
  vehicles: string[];
  /**
   * An array of starship resources that this person has piloted
   */
  starships: string[];
  /**
   * The url of this resource
   */
  url: string;
  /**
   * The ISO 8601 date format of the time that this resource was created.
   */
  created: string;
  /**
   * the ISO 8601 date format of the time that this resource was edited.
   */
  edited: string;
  [k: string]: unknown;
}

/**
 * A planet.
 */
export interface Planet {
  /**
   * The name of this planet.
   */
  name: string;
  /**
   * The diameter of this planet in kilometers.
   */
  diameter: string;
  /**
   * The number of standard hours it takes for this planet to complete a single rotation on its axis.
   */
  rotation_period: string;
  /**
   * The number of standard days it takes for this planet to complete a single orbit of its local star.
   */
  orbital_period: string;
  /**
   * A number denoting the gravity of this planet. Where 1 is normal.
   */
  gravity: string;
  /**
   * The average populationof sentient beings inhabiting this planet.
   */
  population: string;
  /**
   * The climate of this planet. Comma-seperated if diverse.
   */
  climate: string;
  /**
   * the terrain of this planet. Comma-seperated if diverse.
   */
  terrain: string;
  /**
   * The percentage of the planet surface that is naturally occuring water or bodies of water.
   */
  surface_water: string;
  /**
   * An array of Film URL Resources that this planet has appeared in.
   */
  films: string[];
  /**
   * An array of People URL Resources that live on this planet.
   */
  residents: string[];
  /**
   * The hypermedia URL of this resource.
   */
  url: string;
  /**
   * The ISO 8601 date format of the time that this resource was created.
   */
  created: string;
  /**
   * the ISO 8601 date format of the time that this resource was edited.
   */
  edited: string;
  [k: string]: unknown;
}

/**
 * A species within the Star Wars universe
 */
export interface Species {
  /**
   * The name of this species.
   */
  name: string;
  /**
   * The classification of this species.
   */
  classification: string;
  /**
   * The designation of this species.
   */
  designation: string;
  /**
   * The average height of this person in centimeters.
   */
  average_height: string;
  /**
   * The average lifespan of this species in years.
   */
  average_lifespan: string;
  /**
   * A comma-seperated string of common hair colors for this species, none if this species does not typically have hair.
   */
  hair_colors: string;
  /**
   * A comma-seperated string of common skin colors for this species, none if this species does not typically have skin.
   */
  skin_colors: string;
  /**
   * A comma-seperated string of common eye colors for this species, none if this species does not typically have eyes.
   */
  eye_colors: string;
  /**
   * The URL of a planet resource, a planet that this species originates from.
   */
  homeworld: string;
  /**
   * The language commonly spoken by this species.
   */
  language: string;
  /**
   * An array of People URL Resources that are a part of this species.
   */
  people: string[];
  /**
   *  An array of Film URL Resources that this species has appeared in.
   */
  films: string[];
  /**
   * The hypermedia URL of this resource.
   */
  url: string;
  /**
   * The ISO 8601 date format of the time that this resource was created.
   */
  created: string;
  /**
   * The ISO 8601 date format of the time that this resource was edited.
   */
  edited: string;
  [k: string]: unknown;
}

/**
 * A Starship
 */
export interface Starship {
  /**
   * The name of this starship. The common name, such as Death Star.
   */
  name: string;
  /**
   * The model or official name of this starship. Such as T-65 X-wing or DS-1 Orbital Battle Station.
   */
  model: string;
  /**
   * The class of this starship, such as Starfighter or Deep Space Mobile Battlestation.
   */
  starship_class: string;
  /**
   * The manufacturer of this starship. Comma seperated if more than one.
   */
  manufacturer: string;
  /**
   * The cost of this starship new, in galactic credits.
   */
  cost_in_credits: string;
  /**
   * The length of this starship in meters.
   */
  length: string;
  /**
   * The number of personnel needed to run or pilot this starship.
   */
  crew: string;
  /**
   * The number of non-essential people this starship can transport.
   */
  passengers: string;
  /**
   * The maximum speed of this starship in atmosphere. n/a if this starship is incapable of atmosphering flight.
   */
  max_atmosphering_speed: string;
  /**
   * The class of this starships hyperdrive.
   */
  hyperdrive_rating: string;
  /**
   * The Maximum number of Megalights this starship can travel in a standard hour. A Megalight is a standard unit of distance and has never been defined before within the Star Wars universe. This figure is only really useful for measuring the difference in speed of starships. We can assume it is similar to AU, the distance between our Sun (Sol) and Earth.
   */
  MGLT: string;
  /**
   * The maximum number of kilograms that this starship can transport.
   */
  cargo_capacity: string;
  /**
   * The maximum length of time that this starship can provide consumables for its entire crew without having to resupply.
   */
  consumables: string;
  /**
   * An array of Film URL Resources that this starship has appeared in.
   */
  films: string[];
  /**
   * An array of People URL Resources that this starship has been piloted by.
   */
  pilots: string[];
  /**
   * The hypermedia URL of this resource.
   */
  url: string;
  /**
   * The ISO 8601 date format of the time that this resource was created.
   */
  created: string;
  /**
   * the ISO 8601 date format of the time that this resource was edited.
   */
  edited: string;
  [k: string]: unknown;
}

/**
 * A vehicle.
 */
export interface Vehicle {
  /**
   * The name of this vehicle. The common name, such as Sand Crawler.
   */
  name: string;
  /**
   * The model or official name of this vehicle. Such as All Terrain Attack Transport.
   */
  model: string;
  /**
   * The class of this vehicle, such as Wheeled.
   */
  vehicle_class: string;
  /**
   * The manufacturer of this vehicle. Comma seperated if more than one.
   */
  manufacturer: string;
  /**
   * The cost of this vehicle new, in galactic credits.
   */
  cost_in_credits: string;
  /**
   * The length of this vehicle in meters.
   */
  length: string;
  /**
   * The number of personnel needed to run or pilot this vehicle.
   */
  crew: string;
  /**
   * The number of non-essential people this vehicle can transport.
   */
  passengers: string;
  /**
   * The maximum speed of this vehicle in atmosphere.
   */
  max_atmosphering_speed: string;
  /**
   * The maximum number of kilograms that this vehicle can transport.
   */
  cargo_capacity: string;
  /**
   * The maximum length of time that this vehicle can provide consumables for its entire crew without having to resupply.
   */
  consumables: string;
  /**
   * An array of Film URL Resources that this vehicle has appeared in.
   */
  films: string[];
  /**
   * An array of People URL Resources that this vehicle has been piloted by.
   */
  pilots: string[];
  /**
   * The hypermedia URL of this resource.
   */
  url: string;
  /**
   * The ISO 8601 date format of the time that this resource was created.
   */
  created: string;
  /**
   * the ISO 8601 date format of the time that this resource was edited.
   */
  edited: string;
  [k: string]: unknown;
}
